
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patchesStrategicMerge:
  - app-config-patch.yaml

configMapGenerator:
  - name: mysql-config
    files:
      - mysql-values.yaml
